import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";


const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800', '900']
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <header className="h-[120px] w-[1920px] absolute top-0 z-10 flex items-center" >
          <h1 className="h[52px] w-[92px] mt-[33px] mb-[33px] ml-[160px] mr-[148px]">
            <span className="text-[#fbfbfb] text-[36px] font-semibold">Liv</span>
            <span className="text-[#3dcff6] text-[36px] font-semibold">ia</span>
            <span className="text-[#fbfbfb] text-[36px] font-semibold">.</span>
          </h1>
          <NavBar></NavBar>
          <button className="w-[149px] h-[60px] flex justify-center items-center bg-[#5365ef] text-[#fbfbfb] text-[18px] ml-auto mr-[160px]">Contact Us</button>
        </header>
        
        {children}</body>
    </html>
  );
}
